language: go

go:
  - 1.6

# let us have speedy Docker-based Travis workers
# http://docs.travis-ci.com/user/migrating-from-legacy/#tl%3Bdr
sudo: false

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get github.com/GeertJohan/fgt
  - go get github.com/Masterminds/glide

before_script:
  - scripts/travis_etcd.sh 2.2.5

script:
  - ./etcd/etcd >/dev/null 2>&1 &
  - scripts/validate-gofmt
  - go vet ./...
  # - fgt golint ./...
  - glide install
  - go test -v ./dkron

env:
  global:
    - GO15VENDOREXPERIMENT=1
