---
version: "2"
services:
    dkron:
        build: .
        command: dkron agent --server --log-level=debug --bootstrap-expect=1
        ports:
            - "8080:8080"
            - "8946"
            - "6868"
        environment:
            - GODEBUG=netdns=go

    dkron-server:
        build: .
        command: dkron agent --server --retry-join=dkron:8946 --log-level=debug --bootstrap-expect=3
        ports:
            - "8080"
            - "8946"
            - "6868"
        environment:
            - GODEBUG=netdns=go

    dkron-agent:
        command: dkron agent --retry-join=dkron:8946 --log-level=debug --tag agent=true
        build: .
        ports:
            - "8946"
            - "6868"
        environment:
            - GODEBUG=netdns=go

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
            - "1025:1025"
