
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/kardianos/osext"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/armon/circbuf"
  branch = "master"

[[constraint]]
  name = "github.com/armon/go-metrics"
  branch = "master"

[[constraint]]
  name = "github.com/abronan/leadership"
  branch = "master"

[[constraint]]
  name = "github.com/abronan/valkeyrie"
  branch = "master"

[[constraint]]
  name = "github.com/gin-contrib/multitemplate"
  branch = "master"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "^1.2"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/go-syslog"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/memberlist"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/serf"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/jordan-wright/email"
  branch = "master"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  revision = "525bedee691b5a8df547cb5cf9f86b7fb1883e24"

[[constraint]]
  name = "github.com/mitchellh/cli"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "^1.0.2"

[[override]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.1"

[[override]]
  name = "github.com/coreos/etcd"
  version = "^3.0.17"

[[override]]
  name = "github.com/ugorji/go"
  revision = "f1f1a805ed361a0e078bb537e4ea78cd37dcf065"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.13.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.1.0"
