
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/armon/circbuf"

[[constraint]]
  name = "github.com/armon/go-metrics"

[[constraint]]
  name = "github.com/docker/leadership"

[[constraint]]
  name = "github.com/abronan/libkv"
  revision = "5e4bb288a9a74320bb03f5c18d6bdbab0d8049de"

[[constraint]]
  name = "github.com/gin-contrib/multitemplate"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"

[[constraint]]
  name = "github.com/hashicorp/go-syslog"

[[constraint]]
  name = "github.com/hashicorp/memberlist"

[[constraint]]
  name = "github.com/hashicorp/serf"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/jordan-wright/email"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  revision = "525bedee691b5a8df547cb5cf9f86b7fb1883e24"

[[constraint]]
  name = "github.com/mitchellh/cli"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/stretchr/testify"

[[override]]
  name = "github.com/coreos/etcd"
  version = "^3.0.17"

[[override]]
  name = "github.com/ugorji/go"
  revision = "f1f1a805ed361a0e078bb537e4ea78cd37dcf065"
